#!/bin/bash
sudo apt-get update
sudo apt install apache2 -y
sudo apt install php libapache2-mod-php php-mysql -y
sudo apt install php7.2 libapache2-mod-php7.2 php7.2-mysql php-common php7.2-cli php7.2-common php7.2-json php7.2-opcache php7.2-readline -y
cd /tmp
sudo git clone https://github.com/dennisalexandr/adziz4.git
sudo cp -a /tmp/adziz4/. /var/www/html
cd /var/www/html/
sudo rm index.html